-- 3.1
INSERT INTO PERSONS (PERSON_ID, NAME, ADDRESS, PHONE, INCOME, HOBBY, FAVOURITE_MOVIE ) VALUES ( seq_persons.NextVal, 'Varga Márton András', 'Hungária krt 86.', '+36305257026', 100000, 'AdatB', 'cobra11');
--3.2
UPDATE PLACES SET PLACES.PHONE = '(1) 369-3535', PLACES.ADDRESS  = 'IV., Tavasz u. 4/B'  WHERE PLACES.NAME='Ady Endre MK';
--3.3
UPDATE PERSONS SET INCOME = INCOME + 100000 WHERE INCOME >= 19000000;
--3.4
UPDATE VISITS SET AVERAGE_SPENDING = AVERAGE_SPENDING + 900 WHERE AVERAGE_SPENDING >= 8000 AND PLACE_ID IN (
    SELECT PLACES.PLACE_ID FROM PLACES, VISITS WHERE PRICE='high' AND PLACES.PLACE_ID = VISITS.PLACE_ID
 );
--3.5
DELETE FROM VISITS WHERE VISITS.LAST_VISIT < to_date('2016-12-01','yyyy-mm-dd');
--3.6
